apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: u7m4rd3yz-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: u7m4rd3yz-python 
  name: u7m4rd3yz-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: u7m4rd3yz-python 
